#!/bin/bash

upSeconds="$(/usr/bin/cut -d. -f1 /proc/uptime)"
secs=$((${upSeconds}%60))
mins=$((${upSeconds}/60%60))
hours=$((${upSeconds}/3600%24))
days=$((${upSeconds}/86400))
UPTIME=`printf "%d days, %02dh%02dm%02ds" "$days" "$hours" "$mins" "$secs"`

# get the load averages
read one five fifteen rest < /proc/loadavg

echo "$(tput setaf 2)
Date...............: `date +"%A, %e %B %Y, %r"`
System.............: `uname -nsrmo`
IP Addresses.......: `ip a | grep glo | awk '{print $2}' | head -1 | cut -f1 -d/` and `wget -q -O - http://icanhazip.com/ | tail` tailscale `tailscale ip -4`
Uptime.............: ${UPTIME}
Temperature........: `vcgencmd measure_temp | grep  -o -E '[[:digit:]].*'`

$(tput sgr0)"
df -hT /
echo
df -hT /xano_/
echo

tailscale ip -4